export enum BALANCE_STATEMENT_PARTICULAR {
    RESELLER_RECHARGE = 'RESELLER_RECHARGE',
    CLIENT_BIL_RECHARGE = 'CLIENT_BIL_RECHARGE',
    RESELLER_BALANCE_ADJUSTMENT = 'RESELLER_BALANCE_ADJUSTMENT',
    SUB_RESELLER_RECHARGE = 'SUB_RESELLER_RECHARGE',
    SUB_RESELLER_BALANCE_ADJUSTMENT = 'SUB_RESELLER_BALANCE_ADJUSTMENT',
}

export enum DISTRIBUTOR_BALANCE_STATEMENT_PARTICULAR {
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',
    OTC_BILL = 'OTC_BILL',
    MONTHLY_BILL = 'MONTHLY_BILL',
}

export enum GOOGLEMAP_BALANCE_STATEMENT_PARTICULAR {
    INITIALLOAD = 'INITIALLOAD',
    ZOOM = 'ZOOM',
    BOTH = 'BOTH',
    RECHARGE = 'RECHARGE',
    SILICON_RECHARGE = 'SILICON_RECHARGE',
}
export enum GOOGLEMAP_BALANCE_TYPE {
    INITIALLOAD = 'initialLoadBalance',
    ZOOM = 'zoomBalance',
}
