export enum BILLING_TYPE {
    DAILY = 'DAILY',
    MONTHLY_FIXED_DATE = 'MONTHLY_FIXED_DATE',
    MONTHLY_DATE_TO_DATE = 'MONTHLY_DATE_TO_DATE',
}

export enum HOTSPOT_BILLING_TYPE {
    DAILY = 'DAILY',
    MONTHLY = 'MONTHLY',
}
