export enum CONNECTION_TYPE {
    PPPOE = 'PPPOE',
    STATIC = 'STATIC',
    SIMPLE_QUEUE = 'SIMPLE_QUEUE',
    FIREWALL_QUEUE = 'FIREWALL_QUEUE',
    CORE_QUEUE = 'CORE_QUEUE',
    HOTSPOT = 'HOTSPOT',
}
