export enum MESSAGE_GATEWAY_SERVICE {
    REVESMS = 'REVESMS',
}

export enum MESSAGE_TYPE {
    MULTI_CONTACT_WITH_MULTI_CONTENT = 'MULTI_CONTACT_WITH_MULTI_CONTENT',
    MULTI_CONTACT_WITH_SINGLE_CONTENT = 'MULTI_CONTACT_WITH_SINGLE_CONTENT',
    SINGLE_CONTACT_WITH_SINGLE_CONTENT = 'SINGLE_CONTACT_WITH_SINGLE_CONTENT',
}
