export enum ONLINE_BILLING_FOR_ENUM {
    CLIENT_BILL = 'CLIENT_BILL',
    HOTSPOT_BILL = 'HOTSPOT_BILL',
    SHUNNOIT_BILL = 'SHUNNOIT_BILL',
    RESELLER_RECHARGE = 'RESELLER_RECHARGE',
    SUB_RESELLER_RECHARGE = 'SUB_RESELLER_RECHARGE',
    MESSAGE_BILL = 'MESSAGE_BILL',
    DISTRIBUTOR_BILL = 'DISTRIBUTOR_BILL',
    MAP_BALANCE_BILL = 'MAP_BALANCE_BILL',
}
