export enum PRODUCT_ITEM_STATUS_ENUM {
    SOLD = 'SOLD',
    ASSIGNED = 'ASSIGNED',
    IN_STOCK = 'IN_STOCK',
    OUT_OF_STOCK = 'OUT_OF_STOCK',
    RESERVED = 'RESERVED',
    RETURN = 'RETURNED',
}
