export enum RolesEnum {
    SUPER_ADMIN = 'SUPER_ADMIN',
    ADMIN = 'ADMIN',
    MERCHANT = 'MERCHANT',
    RESELLER = 'RESELLER',
    SUB_RESELLER = 'SUB_RESELLER',
    CLIENT = 'CLIENT',
    EMPLOYEE = 'EMPLOYEE',
    DISTRIBUTOR = 'DISTRIBUTOR',
    DISTRIBUTOR_AGENT = 'DISTRIBUTOR_AGENT',
}
