export const permissionSchemaKey = {
    MERCHANT_PERMISSION: 'merchantPermission',
    ZONE_PERMISSIONS: 'zonePermissions',
    SUB_ZONE_PERMISSIONS: 'subZonePermissions',
    BOX_PERMISSIONS: 'boxPermissions',
    ROUTER_PERMISSIONS: 'routerPermissions',
    PACKAGE_PERMISSIONS: 'packagePermissions',
    PACKAGE_ALIAS_PERMISSIONS: 'packageAliasPermissions',
    CLIENT_PERMISSIONS: 'clientPermissions',
    BILL_PERMISSIONS: 'billPermissions',
    CATEGORY_PERMISSIONS: 'categoryPermissions',
    CLIENT_TYPE_PERMISSIONS: 'clientTypePermissions',

    CONNECTION_TYPE_PERMISSIONS: 'connectionTypePermissions',

    EMPLOYEE_PERMISSIONS: 'employeePermissions',
    PRODUCT_PERMISSIONS: 'productPermissions',
    PRODUCT_ITEM_PERMISSIONS: 'productItemPermissions',
    UNIT_PERMISSIONS: 'unitPermissions',
    RESELLER_PERMISSIONS: 'resellerPermissions',
    SUB_RESELLER_PERMISSIONS: 'subResellerPermissions',
    EXPENDITURE_PERMISSIONS: 'expenditurePermissions',
    INCOME_PERMISSIONS: 'incomePermissions',
    INCOME_TYPE_PERMISSIONS: 'incomeTypePermissions',
    EXPENDITURE_TYPE_PERMISSIONS: 'expenditureTypePermissions',
    MANUFACTURER_PERMISSIONS: 'manufacturerPermissions',
    CASHBOX_PERMISSIONS: 'cashboxPermissions',
    PURCHASE_PERMISSIONS: 'purchasePermissions',
    PAY_HEAD: 'payHead',
    DEPOSIT: 'depositPermissions',
    SALARY: 'salaryPermissions',
    BRAND: 'brandPermissions',
    SALE_PERMISSION: 'salePermission',
    SUPPLIER_PERMISSION: 'supplierPermission',
    ADMIN_PERMISSION: 'adminPermission',
};
